version: "3.10"
services:
  face-recog:
    image: "indobertapi"
    container_name: main
    restart: "always"
    build: .
    ports:
      - "2323:2323"
    volumes:
      - .:/code
    environment:
      - LOG_LEVEL=debug
